package org.itson.domino.matchEndingRequest.mvc;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import org.itson.domino.singleton.ButtonStyleSingleton;
import org.itson.domino.singleton.TaskbarButtonSingleton;
import org.itson.domino.singleton.FontSingleton;
import org.itson.domino.singleton.LookAndFeelSingleton;

public class FrmMatchEndingRequestView extends javax.swing.JFrame {

    public FrmMatchEndingRequestView() {
        //ESTABLECER LIBRERÍA DE GUI'S
        LookAndFeelSingleton.getInstance();
        
        //INICIO DE COMPONENTES
        initComponents();
        
        //APLICACIÓN DE ESTILOS
        applyCustomFonts();
        applyButtonStyles();
        
        //UBICACIÓN DE LA VENTANA
        setLocationRelativeTo(null);
    }
    
    public void addNextFormButtonListener(ActionListener listener) {
        btnEndMatch.addActionListener(listener);
    }
    
    public void addPrevFormButtonListener(ActionListener listener) {
        btnContinueMatch.addActionListener(listener);
    }

    private void applyCustomFonts() {
        FontSingleton customFont = FontSingleton.getInstance();
        applyFontToComponents(customFont, "Evil Empire", 80f, lblDomino);
        applyFontToComponents(customFont, "Evil Empire", 30f, lblPlayers, lblFichas, btnEndMatch, btnContinueMatch, lblPlayer, lblQuestion, lblHas);
    }

    private void applyFontToComponents(FontSingleton fontSingleton, String fontName, float size, JComponent... components) {
        for (JComponent component : components) {
            component.setFont(fontSingleton.getFont(fontName, size));
        }
    }
    
    private void applyButtonStyles() {
        ButtonStyleSingleton style = ButtonStyleSingleton.getInstance();

        style.applyButtonStyle(btnEndMatch);
        style.applyButtonStyle(btnContinueMatch);
    }
    
    /**
     * Creates new form FrmBienvenida
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDomino = new javax.swing.JLabel();
        btnEndMatch = new javax.swing.JButton();
        btnContinueMatch = new javax.swing.JButton();
        lblFichas = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblPlayers = new javax.swing.JLabel();
        lblHas = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDomino.setFont(new java.awt.Font("Roboto", 0, 80)); // NOI18N
        lblDomino.setText("Espera.");
        jPanel1.add(lblDomino, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 100));

        btnEndMatch.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        btnEndMatch.setText("Sí. Deseo terminar la partida");
        btnEndMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndMatchActionPerformed(evt);
            }
        });
        jPanel1.add(btnEndMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 400, -1));

        btnContinueMatch.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        btnContinueMatch.setText("No. Deseo continuar la partida");
        btnContinueMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueMatchActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinueMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 400, -1));

        lblFichas.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        lblFichas.setText("propuesto terminar la partida en este punto.");
        jPanel1.add(lblFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lblPlayer.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        lblPlayer.setText("El jugador ");
        jPanel1.add(lblPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblPlayers.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        lblPlayers.setText("xxxxxxxxxxxxxxxxxxx");
        jPanel1.add(lblPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        lblHas.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        lblHas.setText("ha");
        jPanel1.add(lblHas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        lblQuestion.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        lblQuestion.setText("¿Deseas terminar la partida?");
        jPanel1.add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgrounds/matchEndingRequest.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEndMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEndMatchActionPerformed

    private void btnContinueMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinueMatchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinueMatch;
    private javax.swing.JButton btnEndMatch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDomino;
    private javax.swing.JLabel lblFichas;
    private javax.swing.JLabel lblHas;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayers;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
