package org.itson.domino.welcome.mvc;

import DTOs.Acciones;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import org.itson.domino.constants.IconPaths;
import org.itson.domino.managers.ResourceLoader;
import org.itson.domino.singleton.ButtonStyleSingleton;
import org.itson.domino.singleton.TaskbarButtonSingleton;
import org.itson.domino.singleton.FontSingleton;
import org.itson.domino.singleton.LookAndFeelSingleton;

public class FrmWelcomeView extends javax.swing.JFrame implements Observer.Vista.ObserverFrmWelcomeView{

    private FrmWelcomeModel model;
    
    public FrmWelcomeView(FrmWelcomeModel model) {
        //instancia del modelo;        
        this.model = model;
        
        //ESTABLECER LIBRERÍA DE GUI'S
        LookAndFeelSingleton.getInstance();
        
        //INICIO DE COMPONENTES
        initComponents();
        
        //APLICACIÓN DE ESTILOS
        applyCustomFonts();
        applyButtonStyles();
        applyIconsAndBackground();
        
        //UBICACIÓN DE LA VENTANA
        setLocationRelativeTo(null);
        
        //FUNCIONES DE LOS BOTONES DE LA BARRA DE TAREAS
        TaskbarButtonSingleton taskbarButtonSIngleton = TaskbarButtonSingleton.getInstance();
        taskbarButtonSIngleton.addCloseButton(btnClose, this);
        taskbarButtonSIngleton.addMinimizeButton(btnMinimize, this);
    }

    
        private void applyButtonStyles() {
        ButtonStyleSingleton style = ButtonStyleSingleton.getInstance();
        
        style.applyButtonStyle(btnNextForm);
        style.applyButtonStyle(btnClose);
        style.applyButtonStyle(btnMinimize);
        style.applyButtonStyle(btnBuscarPartida);
    }
        
    private void applyIconsAndBackground() {
        try {
            // Aplicar íconos
            btnClose.setIcon(ResourceLoader.loadIcon(IconPaths.CLOSE_ICON, 24, 24));
            btnMinimize.setIcon(ResourceLoader.loadIcon(IconPaths.MINIMIZE_ICON, 24, 24));

            // Aplicar fondo
            lblBackground.setIcon(ResourceLoader.loadBackground(IconPaths.COMMON_BG, 1200, 700));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public void addNextFormButtonListener(ActionListener listener) {
        btnNextForm.addActionListener(listener);
    }
    
    public void addBuscarFormBotonListener(ActionListener listener) {
        btnBuscarPartida.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDomino = new javax.swing.JLabel();
        btnBuscarPartida = new javax.swing.JButton();
        btnNextForm = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDomino.setFont(new java.awt.Font("Roboto", 0, 80)); // NOI18N
        lblDomino.setText("Domino - Vice City Edition");
        jPanel1.add(lblDomino, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        btnBuscarPartida.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        btnBuscarPartida.setText("Buscar partida");
        jPanel1.add(btnBuscarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 320, 70));

        btnNextForm.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        btnNextForm.setText("iniciar");
        jPanel1.add(btnNextForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 190, 70));

        btnClose.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 50, 50));

        btnMinimize.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 50, 50));

        lblBackground.setText("jLabel2");
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void applyCustomFonts() {
        FontSingleton customFont = FontSingleton.getInstance();
        applyFontToComponents(customFont, "Evil Empire", 80f, lblDomino);
        applyFontToComponents(customFont, "Evil Empire", 30f,  btnNextForm);
        applyFontToComponents(customFont, "Evil Empire", 30f,  btnBuscarPartida);
    }

    private void applyFontToComponents(FontSingleton fontSingleton, String fontName, float size, JComponent... components) {
        for (JComponent component : components) {
            component.setFont(fontSingleton.getFont(fontName, size));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPartida;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnNextForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDomino;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarVista(Object object) {
      if(object instanceof Acciones){
           if (object instanceof Acciones) {
                Acciones accion = (Acciones) object;
                
                if (accion== accion.CERRARVENTANA) {
                    
                    this.dispose();
                }
            }
      }
    }
}
